# Generated by Django 4.2.16 on 2024-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bas_dt', models.CharField(max_length=8)),
                ('idx_nm', models.CharField(max_length=100)),
                ('idx_csf', models.CharField(max_length=50)),
                ('epy_itms_cnt', models.IntegerField()),
                ('clpr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flt_rt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mkp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hipr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lopr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trqu', models.BigIntegerField()),
                ('tr_prc', models.BigIntegerField()),
                ('lstg_mrkt_tot_amt', models.BigIntegerField()),
            ],
        ),
    ]
