# Generated by Django 4.2.16 on 2024-11-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='bkpr',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='장부가격'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_nm',
            field=models.CharField(max_length=50, verbose_name='통화명'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_unit',
            field=models.CharField(max_length=10, verbose_name='통화 단위'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='deal_bas_r',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='매매기준율'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_bkpr',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='한국은행 장부가격'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_deal_bas_r',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='한국은행 매매기준율'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ten_dd_efee_r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='10일환가료율'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ttb',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='전신환(송금) 받으실 때'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='전신환(송금) 보내실 때'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='yy_efee_r',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='년환가료율'),
        ),
    ]
