# Generated by Django 4.2.16 on 2024-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_exchange_bkpr_alter_exchange_cur_nm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='bkpr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_nm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='cur_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='deal_bas_r',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_bkpr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='kftc_deal_bas_r',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ten_dd_efee_r',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='ttb',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='tts',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='yy_efee_r',
            field=models.CharField(max_length=100),
        ),
    ]
