# Generated by Django 4.2.16 on 2024-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklist',
            name='bas_dt',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='clpr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='epy_itms_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='flt_rt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='hipr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='idx_csf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='lopr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='lstg_mrkt_tot_amt',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='mkp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='tr_prc',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='trqu',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='vs',
            field=models.FloatField(default=0.0),
        ),
    ]
