# Generated by Django 4.2.16 on 2024-11-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribedproduct',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
