# Generated by Django 4.2.16 on 2024-11-24 06:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bankings', '0002_productreview_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
