# Generated by Django 4.2.16 on 2024-11-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_exchange_bkpr_alter_exchange_cur_nm_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exchange',
            new_name='ExchangeList',
        ),
    ]
