import { useEffect, useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import api, { authConfig, clearSession } from './api.js';

const formatNumber = (value) => Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function App() {
  const [chatOpen, setChatOpen] = useState(false);
  const [loggedIn, setLoggedIn] = useState(Boolean(localStorage.getItem('token')));
  const logout = async () => { try { await api.post('/accounts/logout/', {}, authConfig()); } catch {} clearSession(); setLoggedIn(false); };
  return <><Header loggedIn={loggedIn} logout={logout} openChat={() => setChatOpen(true)} />
    <main className="app-content"><Routes>
      <Route path="/" element={<Navigate replace to="/main" />} />
      <Route path="/main" element={<Home />} />
      <Route path="/productList" element={<Products />} />
      <Route path="/productcompare" element={<Compare />} />
      <Route path="/recommendation" element={<Recommendation />} />
      <Route path="/exchange" element={<Exchange />} />
      <Route path="/nearBank" element={<BankMap />} />
      <Route path="/community" element={<Community />} />
      <Route path="/news" element={<News />} />
      <Route path="/survey" element={<Survey />} />
      <Route path="/mypage/*" element={<MyPage loggedIn={loggedIn} />} />
      <Route path="/user/update" element={<Profile />} />
      <Route path="/login" element={<Auth mode="login" onSuccess={() => setLoggedIn(true)} />} />
      <Route path="/signup" element={<Auth mode="signup" onSuccess={() => setLoggedIn(true)} />} />
      <Route path="*" element={<Navigate replace to="/main" />} />
    </Routes></main>
    <button className="scroll-top" aria-label="맨 위로" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}>↑</button>
    {chatOpen && <Chat close={() => setChatOpen(false)} />}
  </>;
}

function Header({ loggedIn, logout, openChat }) {
  const links = [['/productList', '예·적금'], ['/productcompare', '상품 비교'], ['/recommendation', '맞춤 추천'], ['/exchange', '환율'], ['/nearBank', '영업점 찾기']];
  return <header className="site-header"><div className="utility"><div><span>고객센터 1588-0000</span><div>{loggedIn ? <button onClick={logout}>로그아웃</button> : <><Link to="/login">로그인</Link><Link to="/signup">회원가입</Link></>}<Link to="/mypage">마이페이지</Link></div></div></div><div className="nav-wrap"><Link className="brand" to="/main"><img src="/src/assets/mainlogo.png" alt="WWW 금융"/><small>WEALTH WITH YOU</small></Link><nav>{links.map(([to, label]) => <NavLink key={to} to={to}>{label}</NavLink>)}</nav><button className="chat-trigger" onClick={openChat}>상담하기</button></div></header>;
}

function Home() {
  const [markets, setMarkets] = useState([]); const [news, setNews] = useState([]);
  useEffect(() => { api.get('/markets/indices/').then(({ data }) => setMarkets(Object.entries(data).map(([name, item]) => ({ name, price: formatNumber(item.current_price), change: Number(item.percentage_change || 0) })))).catch(() => setMarkets([{ name: 'S&P 500', price: '4,500.23', change: .85 }, { name: 'NASDAQ', price: '15,000.45', change: -.32 }, { name: 'DOW JONES', price: '35,200.00', change: 1.2 }, { name: 'KOSPI', price: '2,500.00', change: -.5 }])); api.get('/economics/news-get-data/').then(({ data }) => setNews(data.slice(0, 3))).catch(() => {}); }, []);
  const today = new Intl.DateTimeFormat('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' }).format(new Date());
  return <div className="home"><section className="welcome"><div><span className="eyebrow">● TODAY'S FINANCIAL BRIEF</span><h1>더 현명한 금융의 시작, <em>WWW</em>와 함께하세요.</h1></div><p><small>오늘의 금융</small>{today}</p></section><Hero/>
    <section className="card"><SectionTitle eyebrow="MARKET WATCH" title="세계 증시" extra={<span className="live">● 실시간 시세</span>}/><div className="market-grid">{markets.map(m => <article className="market" key={m.name}><small>{m.name}</small><b>{m.price}</b><span className={m.change >= 0 ? 'up' : 'down'}>{m.change >= 0 ? '▲' : '▼'} {Math.abs(m.change).toFixed(2)}%</span></article>)}</div></section>
    <section className="two-col"><article className="card"><SectionTitle eyebrow="INSIGHT" title="금융 뉴스" link="/news"/>{news.length ? <div className="news-list">{news.map((n, i) => <Link to="/news" className="news-item" key={i}><b>0{i + 1}</b><span><strong>{stripHtml(n.title)}</strong><small>{clip(stripHtml(n.description), 60)}</small></span>›</Link>)}</div> : <p className="muted">새로운 금융 뉴스를 불러오고 있습니다.</p>}</article><article className="recommend"><span className="eyebrow">● PERSONAL FINANCE</span><h2>나에게 맞는<br/>금융 상품 찾기</h2><p>간단한 질문으로 내 금융 성향에 꼭 맞는<br/>예·적금 상품을 추천해 드립니다.</p><Link to="/recommendation" className="light-btn">맞춤 상품 추천 →</Link></article></section>
    <section className="card"><SectionTitle eyebrow="BRANCH FINDER" title="가까운 금융 파트너를 만나보세요"/><BankMap compact/></section></div>;
}
function Hero() { return <section className="hero"><div><span className="eyebrow">● SMART FINANCE</span><h2>금융의 모든 순간을<br/><em>더 쉽게, 더 가까이</em></h2><p>환율부터 맞춤 상품까지, 필요한 금융 정보를 한 곳에서 만나보세요.</p><Link to="/exchange" className="light-btn">환율 정보 확인 →</Link></div><div className="hero-orb">₩</div></section>; }
function SectionTitle({ eyebrow, title, link, extra }) { return <div className="section-title"><div><span className="eyebrow">● {eyebrow}</span><h2>{title}</h2></div>{extra || (link && <Link to={link}>전체보기 ↗</Link>)}</div>; }

function useProducts() { const [deposits, setDeposits] = useState([]); const [savings, setSavings] = useState([]); useEffect(() => { const load = () => Promise.all([api.get('/bankings/deposit-get-products/'), api.get('/bankings/saving-get-products/')]).then(([d, s]) => { setDeposits(d.data); setSavings(s.data); return [d.data, s.data]; }); load().then(([d, s]) => { if (d.length || s.length) return; return Promise.allSettled([api.get('/bankings/deposit-fetch-data/'), api.get('/bankings/saving-fetch-data/')]).then(load); }).catch(() => {}); }, []); return { deposits, savings }; }
function Products() { const { deposits, savings } = useProducts(); const [tab, setTab] = useState('deposit'); const [page, setPage] = useState(1); const [detail, setDetail] = useState(null); const list = tab === 'deposit' ? deposits : savings; const rows = list.slice((page - 1) * 10, page * 10); return <section className="page card"><PageHead title="예금 · 적금 상품" text="금리와 조건을 한눈에 비교해 보세요."/><Tabs tab={tab} setTab={x => { setTab(x); setPage(1); }}/>{rows.map(p => <article className="product" key={p.fin_prdt_cd}><div><small>{p.kor_co_nm}</small><h3>{p.fin_prdt_nm}</h3><p>가입기간: {joinPeriod(p.etc_note)}</p></div><button className="outline" onClick={() => setDetail(p)}>상세 보기</button></article>)}<Pagination page={page} total={Math.ceil(list.length / 10)} setPage={setPage}/>{detail && <Modal title={detail.fin_prdt_nm} close={() => setDetail(null)}><p><b>상품 형태</b> {detail.join_way}</p><p><b>가입 조건</b> {detail.join_member}</p><p><b>우대 조건</b> {detail.spcl_cnd}</p><p><b>만기 이율</b> {detail.mtrt_int}</p></Modal>}</section>; }
function Compare() { const { deposits, savings } = useProducts(); const [tab, setTab] = useState('deposit'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState([]); const [chart, setChart] = useState(false); const list = (tab === 'deposit' ? deposits : savings).filter(p => `${p.kor_co_nm} ${p.fin_prdt_nm}`.toLowerCase().includes(query.toLowerCase())); const toggle = p => setSelected(old => old.includes(p) ? old.filter(x => x !== p) : old.length === 3 ? old : [...old, p]); return <section className="page card"><PageHead title="금융 상품 비교" text="최대 세 개의 상품을 선택해 금리를 비교하세요."/><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="은행명 또는 상품명을 검색하세요"/><Tabs tab={tab} setTab={x => { setTab(x); setSelected([]); setChart(false); }}/><p className="muted">선택된 상품: {selected.length} / 3</p><div className="compare-grid">{list.slice(0, 12).map(p => <button key={p.fin_prdt_cd} className={selected.includes(p) ? 'compare-item selected' : 'compare-item'} onClick={() => toggle(p)}><small>{p.kor_co_nm}</small><b>{p.fin_prdt_nm}</b></button>)}</div><button className="primary wide" disabled={selected.length < 2} onClick={() => setChart(true)}>선택 상품 비교하기</button>{chart && <RateChart products={selected} tab={tab}/>}</section>; }
function RateChart({ products, tab }) { const periods = [...new Set(products.flatMap(p => (tab === 'deposit' ? p.deposit_options : p.saving_options || []).map(o => o.save_trm)))].sort((a,b) => a-b); return <div className="chart"><h3>{tab === 'deposit' ? '예금' : '적금'} 상품 금리 비교</h3>{periods.map(period => <div className="chart-row" key={period}><b>{period}개월</b>{products.map(p => { const option = (tab === 'deposit' ? p.deposit_options : p.saving_options || []).find(o => o.save_trm === period); const rate = Number(option?.intr_rate2 || 0); return <span key={p.fin_prdt_cd} style={{ width: `${Math.max(rate * 16, 28)}%` }}>{rate}%</span>; })}</div>)}</div>; }

function Exchange() { const [rates, setRates] = useState([]); const [amount, setAmount] = useState(''); const [from, setFrom] = useState('USD'); const [to, setTo] = useState('KRW'); const [result, setResult] = useState(''); useEffect(() => { api.get('/currencies/exchange-get-data/').then(r => setRates(r.data)).catch(() => {}); }, []); const calculate = () => api.post('/currencies/exchange-calculate/', { amount, from_currency: from, to_currency: to }).then(r => setResult(r.data.converted_amount)).catch(() => setResult('계산 실패')); return <section className="page card"><PageHead title="환율 정보" text="주요 통화의 매매기준율과 환율을 확인하세요."/><div className="calculator"><input type="number" value={amount} onChange={e => setAmount(e.target.value)} placeholder="변환 금액"/><select value={from} onChange={e => setFrom(e.target.value)}>{rates.map(x => <option key={x.cur_unit}>{x.cur_unit}</option>)}</select><button className="outline" onClick={() => { setFrom(to); setTo(from); }}>⇄</button><select value={to} onChange={e => setTo(e.target.value)}>{rates.map(x => <option key={x.cur_unit}>{x.cur_unit}</option>)}</select><button className="primary" onClick={calculate}>계산하기</button>{result && <strong>{result} {to}</strong>}</div><RateTable rows={rates}/></section>; }
function RateTable({ rows }) { return <div className="table-wrap"><table><thead><tr><th>통화 단위</th><th>통화명</th><th>매매기준율</th><th>장부가격</th></tr></thead><tbody>{rows.map(r => <tr key={r.cur_unit}><td>{r.cur_unit}</td><td>{r.cur_nm}</td><td>{r.deal_bas_r}</td><td>{r.bkpr}</td></tr>)}</tbody></table></div>; }
function Recommendation() { const nav = useNavigate(); const [items, setItems] = useState({ deposits: [], savings: [] }); const [loading, setLoading] = useState(true); const [hasSurvey, setHasSurvey] = useState(true); const loggedIn = Boolean(localStorage.getItem('token')); useEffect(() => { if (!loggedIn) { setLoading(false); setHasSurvey(false); return; } api.get('/recommendations/recommend/', authConfig()).then(r => setItems({ deposits: r.data.deposit_recommendations || [], savings: r.data.saving_recommendations || [] })).catch(error => { if (error.response?.status === 404) setHasSurvey(false); }).finally(() => setLoading(false)); }, [loggedIn]); if (!loggedIn || (!loading && (!hasSurvey || (!items.deposits.length && !items.savings.length)))) return <section className="page card empty"><h2>맞춤 추천을 준비하고 있어요</h2><p>{loggedIn ? '금융 성향 설문을 완료하면 나에게 맞는 상품을 추천해 드립니다.' : '로그인 후 금융 성향 설문을 완료해 주세요.'}</p><button className="primary" onClick={() => nav(loggedIn ? '/survey' : '/login')}>{loggedIn ? '설문 시작하기' : '로그인하기'}</button></section>; return <section className="page card"><PageHead title="맞춤 금융 상품 추천" text="내 금융 성향을 기반으로 선별한 상품입니다."/>{loading ? <p>불러오는 중...</p> : ['deposits', 'savings'].map(type => <div className="recommend-products" key={type}><h2>추천 {type === 'deposits' ? '예금' : '적금'} 상품</h2>{items[type].map(p => <article className="product" key={p.fin_prdt_cd}><div><small>{p.kor_co_nm}</small><h3>{p.fin_prdt_nm}</h3></div><b>최고 금리 {p.intr_rate2}%</b></article>)}</div>)}</section>; }
function BankMap({ compact = false }) { const nav = useNavigate(); return <div className={compact ? 'map compact' : 'map'}><div><b>내 주변 영업점</b><p>현재 위치를 기반으로 가까운 은행을 찾아보세요.</p></div><button className="primary" onClick={() => compact ? nav('/nearBank') : window.open('https://map.kakao.com', '_blank')}>영업점 찾기 →</button></div>; }
function News() { const [news, setNews] = useState([]); useEffect(() => { api.get('/economics/news-get-data/').then(r => setNews(r.data)).catch(() => {}); }, []); return <section className="page card"><PageHead title="금융 뉴스" text="오늘의 경제와 금융 소식을 확인하세요."/>{news.map((n, i) => <article className="news-item full" key={i}><b>{String(i + 1).padStart(2, '0')}</b><span><strong>{stripHtml(n.title)}</strong><small>{stripHtml(n.description)}</small></span></article>)}</section>; }
function Community() { const [reviews, setReviews] = useState([]); useEffect(() => { api.get('/bankings/reviews/', authConfig()).then(r => setReviews(r.data)).catch(() => {}); }, []); return <section className="page card"><PageHead title="금융 리뷰 커뮤니티" text="상품을 이용한 고객의 솔직한 경험을 만나보세요."/>{reviews.length ? reviews.map(r => <article className="review" key={r.id}><h3>{r.title || r.product_name || '상품 리뷰'}</h3><p>{r.content}</p><small>♥ {r.like_count || 0}</small></article>) : <p className="muted">등록된 리뷰가 없습니다.</p>}</section>; }
const surveyFields = [
  ['age_group', '연령대', ['20대 이하', '30대', '40대', '50대 이상']], ['income_source', '주요 소득원', ['급여', '사업', '연금', '기타']], ['asset_size', '금융 자산 규모', ['1천만원 미만', '1천만~5천만원', '5천만~1억원', '1억원 이상']], ['financial_purpose', '금융 목표', ['목돈 마련', '노후 준비', '주택 자금', '단기 운용']], ['important_factor', '상품 선택 시 중요 요소', ['금리', '안정성', '유동성', '혜택']], ['recent_investment', '최근 투자 경험', ['있음', '없음']], ['financial_products', '관심 금융 상품', ['예금', '적금', '예·적금 모두', '투자 상품']], ['preferred_bank', '선호 은행', ['시중은행', '지방은행', '인터넷은행', '상관없음']],
];
function Survey() { const nav = useNavigate(); const [answers, setAnswers] = useState({}); const [error, setError] = useState(''); const submit = async () => { if (!localStorage.getItem('token')) return nav('/login'); if (surveyFields.some(([field]) => !answers[field])) return setError('모든 문항을 선택해 주세요.'); try { await api.post('/surveys/submit-survey/', { ...answers, recent_investment: answers.recent_investment === '있음' }, authConfig()); localStorage.setItem('surveyCompleted', 'true'); nav('/recommendation'); } catch (requestError) { setError(requestError.response?.data?.detail?.error || '설문 저장에 실패했습니다.'); } }; return <section className="page card survey"><PageHead title="금융 성향 설문" text="답변을 서버에 저장해 맞춤 추천에 활용합니다."/>{surveyFields.map(([field, label, options], index) => <label key={field}><b>{index + 1}. {label}</b><select value={answers[field] || ''} onChange={e => setAnswers({ ...answers, [field]: e.target.value })}><option value="">선택하세요</option>{options.map(option => <option key={option}>{option}</option>)}</select></label>)}{error && <p className="error">{error}</p>}<button className="primary" onClick={submit}>추천 결과 보기</button></section>; }
function MyPage({ loggedIn }) { const nav = useNavigate(); const [user, setUser] = useState(() => JSON.parse(localStorage.getItem('userInfo') || '{}')); useEffect(() => { if (loggedIn) api.get('/accounts/user_info/', authConfig()).then(({ data }) => { localStorage.setItem('userInfo', JSON.stringify(data.user_info)); setUser(data.user_info); }).catch(() => {}); }, [loggedIn]); if (!loggedIn) return <Navigate to="/login"/>; return <section className="page card"><PageHead title="마이페이지" text="내 금융 활동과 계정 정보를 관리하세요."/><div className="profile"><div className="avatar">{(user.username || 'W')[0]}</div><div><h2>{user.name || user.username || '회원'}님</h2><p>{user.email || '등록된 이메일이 없습니다.'}</p></div></div><button className="outline" onClick={() => nav('/user/update')}>회원 정보 수정</button></section>; }
function Profile() { const nav = useNavigate(); const [form, setForm] = useState({ name: '', email: '' }); useEffect(() => { api.get('/accounts/user_info/', authConfig()).then(({ data }) => setForm({ name: data.user_info.name || '', email: data.user_info.email || '' })).catch(() => nav('/login')); }, [nav]); const save = e => { e.preventDefault(); api.patch('/accounts/user_update/', form, authConfig()).then(({ data }) => { localStorage.setItem('userInfo', JSON.stringify(data.updated_data)); nav('/mypage'); }).catch(() => alert('수정에 실패했습니다.')); }; return <section className="auth card"><PageHead title="회원 정보 수정"/><form onSubmit={save}><input required placeholder="이름" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/><input required type="email" placeholder="이메일" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/><button className="primary">저장하기</button></form></section>; }
function Auth({ mode, onSuccess }) { const nav = useNavigate(); const signup = mode === 'signup'; const [form, setForm] = useState({ username: '', name: '', email: '', password: '', password2: '' }); const [error, setError] = useState(''); const submit = async e => { e.preventDefault(); setError(''); try { const response = signup ? await api.post('/accounts/signup/', { username: form.username, name: form.name, email: form.email, password1: form.password, password2: form.password2 }) : await api.post('/accounts/login/', { username: form.username, password: form.password }); localStorage.setItem('token', response.data.key); const { data } = await api.get('/accounts/user_info/', authConfig()); localStorage.setItem('userInfo', JSON.stringify(data.user_info)); onSuccess(); nav('/main'); } catch (requestError) { setError(requestError.response?.data?.detail?.non_field_errors?.[0] || requestError.response?.data?.detail || '입력 정보를 다시 확인해 주세요.'); } }; return <section className="auth card"><PageHead title={signup ? '회원가입' : '로그인'} text={signup ? 'WWW와 함께 금융 여정을 시작하세요.' : '안전하게 로그인하고 내 금융을 관리하세요.'}/><form onSubmit={submit}><input required placeholder="아이디" onChange={e => setForm({ ...form, username: e.target.value })}/>{signup && <><input required placeholder="이름" onChange={e => setForm({ ...form, name: e.target.value })}/><input required type="email" placeholder="이메일" onChange={e => setForm({ ...form, email: e.target.value })}/></>}<input required type="password" placeholder="비밀번호" onChange={e => setForm({ ...form, password: e.target.value })}/>{signup && <input required type="password" placeholder="비밀번호 확인" onChange={e => setForm({ ...form, password2: e.target.value })}/>} {error && <p className="error">{typeof error === 'string' ? error : '입력 정보를 다시 확인해 주세요.'}</p>}<button className="primary">{signup ? '가입하고 시작하기' : '로그인'}</button></form></section>; }
function Chat({ close }) { const [messages, setMessages] = useState([{ role: 'assistant', content: '안녕하세요! 무엇을 도와드릴까요?' }]); const [text, setText] = useState(''); const [conversationId, setConversationId] = useState(null); const send = async e => { e.preventDefault(); if (!text.trim()) return; const message = text; setMessages(old => [...old, { role: 'user', content: message }]); setText(''); try { const { data } = await api.post('/chats/chat-message/', { message, ...(conversationId && { conversation_id: conversationId }) }, authConfig()); setConversationId(data.conversation_id); setMessages(old => [...old, { role: 'assistant', content: data.message }]); } catch { setMessages(old => [...old, { role: 'assistant', content: '죄송합니다. 문제가 발생했습니다. 로그인 상태와 설정을 확인해 주세요.' }]); } }; return <div className="modal-overlay"><section className="chat"><header><b>WWW 금융 상담</b><button onClick={close}>×</button></header><div className="messages">{messages.map((m, i) => <p className={m.role} key={i}>{m.content}</p>)}</div><form onSubmit={send}><input value={text} onChange={e => setText(e.target.value)} placeholder="궁금한 내용을 입력하세요"/><button>전송</button></form></section></div>; }
function Modal({ title, children, close }) { return <div className="modal-overlay" onClick={close}><section className="modal" onClick={e => e.stopPropagation()}><button className="close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div>; }
function Tabs({ tab, setTab }) { return <div className="tabs"><button className={tab === 'deposit' ? 'active' : ''} onClick={() => setTab('deposit')}>예금</button><button className={tab === 'saving' ? 'active' : ''} onClick={() => setTab('saving')}>적금</button></div>; }
function PageHead({ title, text }) { return <div className="page-head"><h1>{title}</h1>{text && <p>{text}</p>}</div>; }
function Pagination({ page, total, setPage }) { return total > 1 && <div className="pagination"><button disabled={page === 1} onClick={() => setPage(page - 1)}>이전</button><span>{page} / {total}</span><button disabled={page === total} onClick={() => setPage(page + 1)}>다음</button></div>; }
function clip(text = '', count) { return text.length > count ? `${text.slice(0, count)}…` : text; }
function stripHtml(text = '') { return text.replace(/<[^>]*>/g, ''); }
function joinPeriod(note = '') { return note.match(/가입기간: (.+?)\n/)?.[1] || '정보 없음'; }
